# Generated by Django 5.0.2 on 2024-02-15 08:08

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category_name', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Tags',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tag_name', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Blogs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Title', models.CharField(max_length=50)),
                ('Image1', models.ImageField(upload_to='uploads/')),
                ('Body', models.CharField(max_length=500)),
                ('Name', models.CharField(max_length=50)),
                ('Create_at', models.DateTimeField(default=datetime.datetime(2024, 2, 15, 13, 38, 47, 119532))),
                ('Sluglink', models.SlugField(blank=True, max_length=200, null=True, unique=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.category')),
                ('tag', models.ManyToManyField(to='app.tags')),
            ],
        ),
    ]
