# Generated by Django 5.0.2 on 2024-02-15 10:41

import ckeditor.fields
import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_remove_blogs_tag_alter_blogs_create_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogs',
            name='Body',
            field=ckeditor.fields.RichTextField(),
        ),
        migrations.AlterField(
            model_name='blogs',
            name='Create_at',
            field=models.DateTimeField(default=datetime.datetime(2024, 2, 15, 16, 11, 15, 363904)),
        ),
    ]
