# Generated by Django 5.0.2 on 2024-02-15 10:46

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_alter_blogs_body_alter_blogs_create_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogs',
            name='Create_at',
            field=models.DateTimeField(default=datetime.datetime(2024, 2, 15, 16, 16, 45, 745216)),
        ),
        migrations.AlterField(
            model_name='blogs',
            name='Title',
            field=models.CharField(max_length=500),
        ),
    ]
