# Generated by Django 5.0.2 on 2024-02-15 11:07

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_blogs_tag_alter_blogs_create_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogs',
            name='Create_at',
            field=models.DateTimeField(default=datetime.datetime(2024, 2, 15, 16, 37, 38, 476107)),
        ),
        migrations.AlterField(
            model_name='blogs',
            name='tag',
            field=models.CharField(default='', max_length=300, null=True),
        ),
    ]
