# Generated by Django 5.0.2 on 2024-02-16 05:34

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_alter_blogs_create_at_alter_blogs_tag'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blogs',
            name='Title',
        ),
        migrations.AddField(
            model_name='blogs',
            name='First_title',
            field=models.CharField(default='', max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='blogs',
            name='Second_title',
            field=models.CharField(default='', max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='blogs',
            name='Create_at',
            field=models.DateTimeField(default=datetime.datetime(2024, 2, 16, 11, 4, 4, 755835)),
        ),
    ]
