# Generated by Django 5.0.2 on 2024-02-16 07:34

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_remove_blogs_title_blogs_first_title_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('Id', models.IntegerField(primary_key=True, serialize=False)),
                ('Name', models.CharField(default='heading', max_length=30)),
                ('Email', models.EmailField(max_length=254)),
                ('Message', models.CharField(max_length=200)),
            ],
        ),
        migrations.AlterField(
            model_name='blogs',
            name='Create_at',
            field=models.DateTimeField(default=datetime.datetime(2024, 2, 16, 13, 4, 1, 947816)),
        ),
    ]
