# Generated by Django 5.0.2 on 2024-02-16 09:48

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_contact_alter_blogs_create_at'),
    ]

    operations = [
        migrations.CreateModel(
            name='Banner',
            fields=[
                ('Id', models.IntegerField(primary_key=True, serialize=False)),
                ('Title', models.CharField(default='heading', max_length=25)),
                ('Description', models.CharField(max_length=100)),
                ('Image', models.ImageField(upload_to='uploads/')),
            ],
        ),
        migrations.AlterField(
            model_name='blogs',
            name='Create_at',
            field=models.DateTimeField(default=datetime.datetime(2024, 2, 16, 15, 18, 31, 66735)),
        ),
    ]
