# Generated by Django 5.0.2 on 2024-02-19 05:25

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_portfolio_alter_blogs_create_at'),
    ]

    operations = [
        migrations.CreateModel(
            name='About',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('About_Title', models.CharField(max_length=200)),
                ('About_Long_Desc', models.CharField(max_length=500)),
                ('About_Image', models.ImageField(upload_to='uploads/')),
            ],
        ),
        migrations.RenameField(
            model_name='portfolio',
            old_name='Description',
            new_name='Port_Description',
        ),
        migrations.RenameField(
            model_name='portfolio',
            old_name='Title',
            new_name='Port_Title',
        ),
        migrations.RenameField(
            model_name='portfolio',
            old_name='Images',
            new_name='Portfolio_Image',
        ),
        migrations.AlterField(
            model_name='blogs',
            name='Create_at',
            field=models.DateTimeField(default=datetime.datetime(2024, 2, 19, 10, 55, 4, 901248)),
        ),
    ]
