# Generated by Django 5.0.2 on 2024-02-19 05:46

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0013_rename_about_image_about_abou_image_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogs',
            name='Create_at',
            field=models.DateTimeField(default=datetime.datetime(2024, 2, 19, 11, 16, 8, 384360)),
        ),
    ]
