# Generated by Django 5.0.2 on 2024-02-19 05:53

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0014_alter_blogs_create_at'),
    ]

    operations = [
        migrations.RenameField(
            model_name='about',
            old_name='Abou_Image',
            new_name='About_Image',
        ),
        migrations.RenameField(
            model_name='about',
            old_name='Abou_Long_Desc',
            new_name='About_Long_Desc',
        ),
        migrations.RenameField(
            model_name='about',
            old_name='Abou_Title',
            new_name='About_Title',
        ),
        migrations.AlterField(
            model_name='blogs',
            name='Create_at',
            field=models.DateTimeField(default=datetime.datetime(2024, 2, 19, 11, 23, 45, 94216)),
        ),
    ]
